# Generated by Django 5.2.7 on 2025-12-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tours',
            options={'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
    ]
